### ISSUE TITLE
Unexpected behaviour of TypeOf

### ISSUE THREAD

**Issue by ThomWright** [TypeStrong/ts-expect#11]
Hello, I wonder if you could help me out with something. Either my understanding is incorrect, in which case maybe we could improve the docs to help the next person with the same problem, or something is the wrong way around.

The docs for `TypeOf` are:

```typescript
/**
 * Checks that `T` is of type `U`.
 */
export declare type TypeOf<T, U> = Exclude<U, T> extends never ? true : false;
```

And here is an example of using it which compiles, which I didn't expect:

```typescript
// I would expect true - T is assignable to U
expectType<TypeOf<{a: string; b: string}, {a: string}>>(false)

// I would expect false - T is not assignable to U
expectType<TypeOf<{a: string}, {a: string; b: string}>>(true)
```

I'm assuming that "`T` is of type `U`" is equivalent to saying "`T` is assignable to `U`". 

In this case, `{a: string; b: string}` is assignable to `{a: string}` but not vice versa. However, the assertion seems to work the other way.

Is my thinking backwards, or is this backwards?

As an aside, I wonder if some tips or best practices could be added to the README. Including when it might be best to use each of the three exports - `expectType` vs `TypeEqual` vs `TypeOf`.

I think a good example tip would be how to check for `unknown`, which tripped me up:

```typescript
// this is no good
expectType<unknown>("hello") // passes, oh no

// this works
expectType<TypeEqual<unknown, string>>(true) // fails, as expected
```

Thank you for this library by the way. It's been really quick to get going.

**Comment by blakeembrey** [comment]
Good catch, thanks! This is totally my fault when I wrote the original package and couldn't decide which way to order the arguments. The tests follow what you've said is the case but is unexpected due to the documentation: https://github.com/TypeStrong/ts-expect/blob/081bfd3d5367c4dad203098025a17654727a7e31/src/index.spec.ts#L17-L20. If you're not too worried about the order, I can update the comment and generic names to clarify intent better.

**Comment by blakeembrey** [comment]
Do you want to take a quick look at https://github.com/TypeStrong/ts-expect/pull/12 and let me know if it helps with explaining things? Always happy to take better suggestions for the documentation or generic naming.

**Comment by blakeembrey** [comment]
> As an aside, I wonder if some tips or best practices could be added to the README. 

I'd love to improve on this too, sounds like a great idea! Some simple "recipes". One thing to check first, do you think it's useful to do a little pre-amble on the type system? E.g. explain that `unknown` is the top type so everything is assignable to it, while `never` is a bottom type so nothing is assignable to it, with some examples? The most used place I tend to use this library in actual code is actually exhaustive checks asserting I caught everything with `expectType<never>(value)`.

**Comment by ThomWright** [comment]
>do you think it's useful to do a little pre-amble on the type system?

I think this would be excellent. Could also try to 'outsource' the work (linking somewhere) if there's something good and relevant. But, I think it would be better to have here so it can be tailored to the context.

>explain that unknown is the top type so everything is assignable to it, while never is a bottom type so nothing is assignable to it

Seeing this written down it seems almost obvious, but it wasn't top of mind when I was writing the tests, so I think a reminder (or maybe introduction for some!) would be really useful.

>The most used place I tend to use this library in actual code is actually exhaustive checks asserting I caught everything

Interesting! I hadn't considered using it 'inline'. I often use an `assertNever(value)` function though.

I've started using it kinda like a 'unit testing' library to check my types work as expected - see here: https://github.com/ThomWright/balamb/blob/6f5b08a32f83588aa8bf2a35b8300cd35478197f/test/type/index.ts

**Comment by blakeembrey** [comment]
I have a documentation follow up in https://github.com/TypeStrong/ts-expect/pull/13, would you mind taking a look and seeing if it makes sense?

**Comment by ThomWright** [comment]
> I have a documentation follow up in #13, would you mind taking a look and seeing if it makes sense?

Looks great! :+1: from me.
