### ISSUE TITLE
Exhaustive checks example

### ISSUE THREAD

**Issue by ThomWright** [TypeStrong/ts-expect#14]
If you add a return type to the function in the _Exhaustive checks_ example, it no longer compiles:

```ts
type SupportedValue = "a" | "b"

function doSomething(value: SupportedValue): boolean {
  switch (value) {
    case "a":
      return true
    case "b":
      return true
    default:
      expectType<never>(value)
  }
}
```

In order for this to work, `expectType` would need to return `never`, as in [this example](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#union-exhaustiveness-checking).

**Comment by blakeembrey** [comment]
Oh yeah, I should have actually tested the snippet 😄 I think the correct behavior in this snippet is to `return false`, and I can add an `expectNever` function that actually throws and returns `never`.

**Comment by ThomWright** [comment]
Great, thank you.

BTW, I've started sprinkling some type assertions around my codebase and it feels very natural. Really enjoying how much easier it makes it to sense-check my types.
