### ISSUE TITLE
Expect union types exactly

### ISSUE THREAD

**Issue by SevenOutman** [TypeStrong/ts-expect#16]
Hi, I have this case that I want to expect a value to be exactly `number | null` typed. But a plain `number` is passing the assertion

![image](https://user-images.githubusercontent.com/8225666/145331094-3e8139a0-236b-4af3-aa63-c6a55fb16e3a.png)

**Comment by blakeembrey** [comment]
That is expected. A number is of type `number | null`. There's no workaround in TypeScript right now except to use the `TypeEqual` helper documented in the README, e.g. `expectType<TypeEqual<number | null, typeof numberValue>>(true)`. Unfortunately the UX on it not matching isn't great.
