### ISSUE TITLE
test without using yarn link

### ISSUE THREAD

**Issue by dagda1** [TypeStrong/ts-expect#4]
Is there anyway I can test a `.d.ts` file in the same project as the source?

At the moment if my tests, source and declaration file are in the same project I have to:

```javascript
npm link
npm link my-project
npm test
```

Can I somehow test without linking?

**Comment by blakeembrey** [comment]
@dagda1 Can you explain how you use this package or what you described is related?

Edit: Abstractly, you just import and write a `.ts` file like you normally would.

**Comment by dagda1** [comment]
`ts-expect` is being used to test a `.d.ts` file which is included in a javascript only project.  So the only typescript files are the project's declaration file and the test files.

So in order to test it, the project npm link's to itself so module resolution works:

```
import { A } from 'my-project' // without npm link my-project would not get loaded`

describe('Any', () => {
  let a = new A;
  it('creates an Any', () => {
    expectType<A>(a);
  });
```

**Comment by blakeembrey** [comment]
@dagda1 I think we've missed a step, why do you need to `npm link`? Have you tried just importing from the file you're trying to test, e.g. `import { A } from './file'`?

**Comment by dagda1** [comment]
Yes but `'./file'` is a plain js file and ts will try and infer the types from the js file which will result in some loose typing and I would prefer ts to get the types from the `index.d.ts` file which only works (I think) if it is a non-relative reference, i.e. `import { A } from 'my-project'`.

Please feel free to close this as it is not a bug in this project.  `npm link` works but it is a bit annoying.

**Comment by blakeembrey** [comment]
Do you have `allowJs` enabled? I’m confident you can do this without NPM link, I just need to try it out with the same configuration you have.

**Comment by dagda1** [comment]
thank you.  i do have allowjs set to true.  i’m fairly sure relative js imports will be inferred from the file

**Comment by blakeembrey** [comment]
I just created https://github.com/TypeStrong/ts-expect/tree/master/examples/test-definition and it appears to work. Can you verify this looks like your setup? 

Another thing you can do is create `.type-spec.ts` files you ignore in test suites (e.g. it's only for the compiler) and explicitly import from `./example.d` instead. However, I typically find testing runtime and compile time together is effective but understand there's cases where you only want to test the definition file.

**Comment by dagda1** [comment]
I have the same setup as yours but I think in both cases the type is being inferred from the js file and not from the `.d.ts` file.  I could be wrong but I think that is what is happening.

**Comment by blakeembrey** [comment]
That’s not true, you can look at the JS file. I’ve explicitly checked in a file that won’t compile if you remove the definition.

**Comment by dagda1** [comment]
@blakeembrey apologies and thank you for your patience, what is it that maps example.js to the declaration file in example.d.ts?  Is it because they are named the same?

**Comment by blakeembrey** [comment]
Yes, that’s how TypeScript discovers the definition file - it searches for different extensions over the others.

**Comment by dagda1** [comment]
Going to close this, thank you for your patience and help.
